version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://aimecesaire:offer-database-password@db:5432/trades

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: aimecesaire
      POSTGRES_PASSWORD: offer-database-password
      POSTGRES_DB: trades
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: